[general]
bars = 16
sleep_timer = 0
framerate = 60
sensitivity = 150

[input]
method = pipewire

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 12
bar_delimiter = 59
frame_delimiter = 10
channels = mono

[smoothing]
noise_reduction = 0.58
