pragma Singleton

import QtQuick
import Quickshell

// Generated by matugen — do not edit manually, edit the template instead
Singleton {
    readonly property color background: "{{colors.background.default.hex}}"
    readonly property color surface:    "{{colors.surface_container.default.hex}}"
    readonly property color text:       "{{colors.on_surface.default.hex}}"
    readonly property color subtext:    "{{colors.on_surface_variant.default.hex}}"
    readonly property color accent:     "{{colors.primary.default.hex}}"
    readonly property color error:      "{{colors.error.default.hex}}"
    readonly property color warning:    "{{colors.tertiary.default.hex}}"
    readonly property color success:    "{{colors.secondary.default.hex}}"
}
